WIP: boilerplate lambda for metrics cleaning
octo-technology/tezos-link pull request #49
Opened 2020-06-18 15:41 UTC by frankhillard

2020-06-22 10:32 UTC, aboulay commented
[WFD] Wait for dependancies on infrastructure : https://github.com/octo-technology/tezos-link/pull/51

2020-07-03 16:58 UTC, aboulay requested changes
Just update those two short comment and we are fine ! :D Well done !

2020-07-03 16:58 UTC, aboulay commented on cmd/metrics/main.go
> +//var configPath = flag.String("conf", "", "Path to TOML config")
```suggestion

```

2020-07-03 16:58 UTC, aboulay commented on cmd/metrics/main.go
> +/*	log.Print("DB URL", config.ProxyConfig.Database.Url)
Deadcode here ?

2020-07-08 16:20 UTC, frankhillard commented on cmd/metrics/main.go
> +//var configPath = flag.String("conf", "", "Path to TOML config")
comment deleted

2020-07-08 16:20 UTC, frankhillard commented on cmd/metrics/main.go
> +/*	log.Print("DB URL", config.ProxyConfig.Database.Url)
comment deleted

2020-07-08 16:23 UTC, aboulay approved these changes
Well done !

2020-07-08 16:30 UTC, merged